<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>em2devs-todo-worker</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EM2Devs.Todo.Application\EM2Devs.Todo.Application.csproj" />
    <ProjectReference Include="..\EM2Devs.Todo.Infrastructure\EM2Devs.Todo.Infrastructure.csproj" />
    <ProjectReference Include="..\EM2Devs.Todo.ServiceDefaults\EM2Devs.Todo.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.5.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.14" />
  </ItemGroup>
</Project>
