<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.2" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.5.2" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.NodeJS.Extensions" Version="9.9.0" />
    <PackageReference Include="MessagePack" Version="2.5.301" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EM2Devs.Todo.Api\EM2Devs.Todo.Api.csproj" />
    <ProjectReference Include="..\EM2Devs.Todo.Worker\EM2Devs.Todo.Worker.csproj" />
  </ItemGroup>
</Project>
