// <auto-generated />
using System;
using EM2Devs.Todo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EM2Devs.Todo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260417000000_AddUserIdToRecurringTasks")]
    partial class AddUserIdToRecurringTasks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.HasKey("Id");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.RecurringTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pattern");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("recurring_tasks", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.StreakSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentDays")
                        .HasColumnType("integer")
                        .HasColumnName("current_days");

                    b.Property<int>("GraceDaysAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("grace_days_available");

                    b.Property<int>("LongestDays")
                        .HasColumnType("integer")
                        .HasColumnName("longest_days");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<bool>("WasActive")
                        .HasColumnType("boolean")
                        .HasColumnName("was_active");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .IsUnique();

                    b.ToTable("streak_snapshots", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.TodoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedQuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_quest_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Normal")
                        .HasColumnName("difficulty");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<bool>("IsBossTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_boss_task");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium")
                        .HasColumnName("priority");

                    b.Property<int>("RescheduleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reschedule_count");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<Guid?>("SourceRecurringTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_recurring_task_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<string>("WaitingReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("waiting_reason");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SourceRecurringTaskId", "ScheduledDate")
                        .IsUnique()
                        .HasFilter("source_recurring_task_id IS NOT NULL");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.PlayerProfile", b =>
                {
                    b.OwnsOne("EM2Devs.Todo.Domain.ValueObjects.Level", "Level", b1 =>
                        {
                            b1.Property<Guid>("PlayerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("level_value");

                            b1.HasKey("PlayerProfileId");

                            b1.ToTable("player_profiles");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProfileId");

                            b1.OwnsOne("EM2Devs.Todo.Domain.ValueObjects.ExperiencePoints", "CurrentXp", b2 =>
                                {
                                    b2.Property<Guid>("LevelPlayerProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("level_current_xp");

                                    b2.HasKey("LevelPlayerProfileId");

                                    b2.ToTable("player_profiles");

                                    b2.WithOwner()
                                        .HasForeignKey("LevelPlayerProfileId");
                                });

                            b1.Navigation("CurrentXp")
                                .IsRequired();
                        });

                    b.OwnsOne("EM2Devs.Todo.Domain.ValueObjects.Streak", "Streak", b1 =>
                        {
                            b1.Property<Guid>("PlayerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CurrentDays")
                                .HasColumnType("integer")
                                .HasColumnName("streak_current_days");

                            b1.Property<int>("GraceDaysAvailable")
                                .HasColumnType("integer")
                                .HasColumnName("streak_grace_days_available");

                            b1.Property<DateOnly?>("LastActiveDate")
                                .HasColumnType("date")
                                .HasColumnName("streak_last_active_date");

                            b1.HasKey("PlayerProfileId");

                            b1.ToTable("player_profiles");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProfileId");
                        });

                    b.Navigation("Level")
                        .IsRequired();

                    b.Navigation("Streak")
                        .IsRequired();
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.TodoTask", b =>
                {
                    b.OwnsOne("EM2Devs.Todo.Domain.Entities.EstimationRecord", "ActualTimeRecord", b1 =>
                        {
                            b1.Property<Guid>("task_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Estimated")
                                .HasColumnType("integer")
                                .HasColumnName("estimated_minutes");

                            b1.Property<int>("Actual")
                                .HasColumnType("integer")
                                .HasColumnName("actual_minutes");

                            b1.Property<double>("VariancePercent")
                                .HasColumnType("double precision")
                                .HasColumnName("variance_percent");

                            b1.Property<string>("Category")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("category");

                            b1.HasKey("task_id");

                            b1.ToTable("task_actual_time_records");

                            b1.WithOwner()
                                .HasForeignKey("task_id");
                        });

                    b.Navigation("ActualTimeRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
