// <auto-generated />
using System;
using EM2Devs.Todo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EM2Devs.Todo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260408035825_AddBackgroundJobsTables")]
    partial class AddBackgroundJobsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.HasKey("Id");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.RecurringTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("LastGeneratedAt")
                        .HasColumnType("date")
                        .HasColumnName("last_generated_at");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pattern");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("recurring_tasks", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.StreakSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentDays")
                        .HasColumnType("integer")
                        .HasColumnName("current_days");

                    b.Property<int>("GraceDaysAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("grace_days_available");

                    b.Property<int>("LongestDays")
                        .HasColumnType("integer")
                        .HasColumnName("longest_days");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<bool>("WasActive")
                        .HasColumnType("boolean")
                        .HasColumnName("was_active");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .IsUnique();

                    b.ToTable("streak_snapshots", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.TodoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBossTask")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("EM2Devs.Todo.Domain.Entities.PlayerProfile", b =>
                {
                    b.OwnsOne("EM2Devs.Todo.Domain.ValueObjects.Level", "Level", b1 =>
                        {
                            b1.Property<Guid>("PlayerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("level_value");

                            b1.HasKey("PlayerProfileId");

                            b1.ToTable("player_profiles");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProfileId");

                            b1.OwnsOne("EM2Devs.Todo.Domain.ValueObjects.ExperiencePoints", "CurrentXp", b2 =>
                                {
                                    b2.Property<Guid>("LevelPlayerProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("level_current_xp");

                                    b2.HasKey("LevelPlayerProfileId");

                                    b2.ToTable("player_profiles");

                                    b2.WithOwner()
                                        .HasForeignKey("LevelPlayerProfileId");
                                });

                            b1.Navigation("CurrentXp")
                                .IsRequired();
                        });

                    b.OwnsOne("EM2Devs.Todo.Domain.ValueObjects.Streak", "Streak", b1 =>
                        {
                            b1.Property<Guid>("PlayerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CurrentDays")
                                .HasColumnType("integer")
                                .HasColumnName("streak_current_days");

                            b1.Property<int>("GraceDaysAvailable")
                                .HasColumnType("integer")
                                .HasColumnName("streak_grace_days_available");

                            b1.Property<DateOnly?>("LastActiveDate")
                                .HasColumnType("date")
                                .HasColumnName("streak_last_active_date");

                            b1.HasKey("PlayerProfileId");

                            b1.ToTable("player_profiles");

                            b1.WithOwner()
                                .HasForeignKey("PlayerProfileId");
                        });

                    b.Navigation("Level")
                        .IsRequired();

                    b.Navigation("Streak")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
